# Generated by Django 5.1.3 on 2024-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
