# Generated by Django 5.1.3 on 2024-12-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_username_contact_usename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='usename',
        ),
    ]
