# Generated by Django 5.1.3 on 2024-12-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
