# Generated by Django 5.1.3 on 2024-12-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobole',
            new_name='mobile',
        ),
    ]
