# Generated by Django 5.1.3 on 2024-12-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='first_name',
        ),
    ]
