# Generated by Django 3.2 on 2025-05-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
